# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kocli < Formula
  desc ""
  homepage ""
  version "1.3.11"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/10xLabs/kocli/releases/download/v1.3.11/kocli_1.3.11_Linux_arm64.tar.gz"
      sha256 "e2cdd55d9aba79203d3aec88db1b574b69d1f2d8df88481a9efa1c1415b43425"

      def install
        bin.install "ko"
      end
    end
  end

  head "https://github.com/10xLabs/kocli.git"

  depends_on "git"
  depends_on "zsh" => :optional
end
