# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Kocli < Formula
  desc "Internal Kolors CLI"
  homepage "https://github.com/10xLabs/kocli"
  version "1.18.0"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/10xLabs/kocli/releases/download/v1.18.0/kocli_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fff24b72ba0498ca010ea106976190bd0cc24bf421c9fd781e69f2f0dfb15cae"

      def install
        bin.install "ko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/10xLabs/kocli/releases/download/v1.18.0/kocli_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "73975809401d147e14c26086e55ddbb8fafd57f90ed863c123cd381989c8b187"

      def install
        bin.install "ko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/10xLabs/kocli/releases/download/v1.18.0/kocli_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d11938b03b5fdb9e54f368e3e69922da734c06f726ded149cbc8699285329861"

      def install
        bin.install "ko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/10xLabs/kocli/releases/download/v1.18.0/kocli_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e47c5a730748da5c73522e7dcec3e33e88433e28d783934a8725fdb04e96e0ae"

      def install
        bin.install "ko"
      end
    end
  end

  head "https://github.com/10xLabs/kocli.git"

  def caveats
    <<~EOS
      To start using kocli use "ko"
        ko --help
        ko --version
    EOS
  end

  test do
    ko --help
  end
end
