# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Kocli < Formula
  desc "Internal Kolors CLI"
  homepage "https://github.com/10xLabs/kocli"
  version "1.16.0"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/10xLabs/kocli/releases/download/v1.16.0/kocli_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f2c3b217897e266e9c4000672efcd28703b3efcaded2a9dcae2b74dade5a7e74"

      def install
        bin.install "ko"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/10xLabs/kocli/releases/download/v1.16.0/kocli_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c6198fb75ecba66a7f73a84746a67ff1415d98872f660b00b79119a23aa0f2f4"

      def install
        bin.install "ko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/10xLabs/kocli/releases/download/v1.16.0/kocli_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f33381671af73a20efc4db3dbfab356b2f5c9c907b70424b3e24be7e32eef34a"

      def install
        bin.install "ko"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/10xLabs/kocli/releases/download/v1.16.0/kocli_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "648bfe9edcef1c948ec1bd282937bf237b58ad8090f83cb269bc820e99b78a50"

      def install
        bin.install "ko"
      end
    end
  end

  head "https://github.com/10xLabs/kocli.git"

  def caveats
    <<~EOS
      To start using kocli use "ko"
        ko --help
        ko --version
    EOS
  end

  test do
    ko --help
  end
end
